tasks:
    path: /tareas
    controller: App\Controller\TaskController::index

task-detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::detail

task-create:
    path: /crear-tarea
    controller: App\Controller\TaskController::create

task-edit:
    path: /editar-tarea/{id}
    controller: App\Controller\TaskController::edit

task-delete:
    path: /eliminar-tarea/{id}
    controller: App\Controller\TaskController::delete

my-tasks:
    path: /mis-tareas
    controller: App\Controller\TaskController::myTasks

register:
    path: /registro
    controller: App\Controller\UserController::register

login:
    path: /
    controller: App\Controller\UserController::login

logout:
    path: /logout
